# Generated by Django 3.2.7 on 2021-10-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField(blank=True, default=None)),
                ('date_approval', models.DateField(blank=True, default=None)),
                ('document', models.CharField(max_length=500)),
                ('publicity', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('initial', models.IntegerField()),
                ('total', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('ปริญญาตรี', 'ปริญญาตรี'), ('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=50, null=True)),
                ('faculty', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('study_date', models.DateField(blank=True, default=None)),
                ('graduate', models.DateField(blank=True, default=None)),
                ('gpa', models.FloatField()),
                ('honors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.FileField(blank=True, default='default.pdf', null=True, upload_to='uploads/%d/%m/%Y/')),
                ('author', models.CharField(max_length=100)),
                ('date_request', models.DateField(blank=True, default=None)),
                ('date_evaluate', models.DateField(blank=True, default=None)),
                ('date_expire', models.DateField(blank=True, default=None)),
                ('level_evaluate_tech', models.CharField(max_length=100)),
                ('level_evaluate_document', models.CharField(max_length=100)),
                ('no_evaluate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('training_people', models.IntegerField()),
                ('training_time', models.IntegerField()),
                ('seminars_people', models.IntegerField()),
                ('seminars_time', models.IntegerField()),
                ('events_people', models.IntegerField()),
                ('events_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Human_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_PDF', models.FileField(blank=True, default='default.pdf', null=True, upload_to='uploads/%d/%m/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Manpower_Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Manpower_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding_Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('data_request', models.DateField(blank=True, default=None)),
                ('data_request_evaluate', models.DateField(blank=True, default=None)),
                ('data_evaluate', models.DateField(blank=True, default=None)),
                ('data_full_term', models.DateField(blank=True, default=None)),
                ('position_request', models.CharField(max_length=100)),
                ('status_pending', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('id_Position', models.CharField(max_length=20)),
                ('title_name', models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10, null=True)),
                ('name_th', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('personal_type', models.CharField(blank=True, choices=[('พนักงานมหาวิทยาลัย', 'พนักงานมหาวิทยาลัย'), ('ลูกจ้างชั่วคราว', 'ลูกจ้างชั่วคราว')], max_length=255, null=True)),
                ('line_of_work', models.CharField(blank=True, choices=[('วิชาการ', 'วิชาการ'), ('สนับสนุน', 'สนับสนุน')], max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('อาจารย์', 'อาจารย์'), ('เจ้าหน้าที่บริหารงานทั้วไป', 'เจ้าหน้าที่บริหารงานทั้วไป'), ('บุคลากร', 'บุคลากร'), ('นักวิชาการศึกษา', 'นักวิชาการศึกษา'), ('นักวิเคราะห์นโยบายและเเผน', 'นักวิเคราะห์นโยบายและเเผน'), ('นักประชาสัมพันธ์', 'นักประชาสัมพันธ์'), ('นักวิทยาศาสตร์', 'นักวิทยาศาสตร์'), ('นักวิชาการโสตทัศนศึกษา', 'นักวิชาการโสตทัศนศึกษา'), ('นักวิชาการคอมพิวเตอร์', 'นักวิชาการคอมพิวเตอร์'), ('ครู', 'ครู')], max_length=100, null=True)),
                ('academic_position', models.CharField(blank=True, choices=[('ศาสตราจารย์', 'ศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('เชี่ยวชาญ', 'เชี่ยวชาญ'), ('ชำนาญการพิเศษ', 'ชำนาญการพิเศษ'), ('ชำนาญการ', 'ชำนาญการ')], max_length=100, null=True)),
                ('director_position', models.CharField(blank=True, choices=[('คณบดี', 'คณบดี'), ('รองคณบดี', 'รองคณบดี'), ('ผู้ช่วยคณบดี', 'ผู้ช่วยคณบดี'), ('ประธานหลักสูตร', 'ประธานหลักสูตร'), ('หัวหน้างาน', 'หัวหน้างาน')], max_length=100, null=True)),
                ('start_work_date', models.DateField(blank=True, default=None)),
                ('placement_date', models.DateField(blank=True, default=None)),
                ('status_job', models.DateField(blank=True, default=None)),
                ('date_birth', models.DateField(blank=True, default=None)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email_UP', models.EmailField(max_length=255)),
                ('email_private', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('faculty_id', models.CharField(max_length=100)),
                ('id_degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.degree')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_PDF', models.FileField(blank=True, default='default.pdf', null=True, upload_to='uploads/%d/%m/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='Study_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('begin', models.DateField(blank=True, default=None)),
                ('end', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=60)),
                ('extend_time', models.CharField(max_length=50)),
                ('extend_begin', models.CharField(max_length=70)),
                ('extend_end', models.DateField(blank=True, default=None)),
                ('work', models.DateField(blank=True, default=None)),
                ('approval', models.DateField(blank=True, default=None)),
                ('requesting', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Year_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Year_HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Year_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Year_R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Year_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.outstanding_academic')),
                ('id_os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.outstanding_service')),
                ('id_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.year_out')),
            ],
        ),
        migrations.CreateModel(
            name='User_Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.degree')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_master_PDF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
                ('id_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.year_r')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Manpower_SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_MS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Manpower_AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_MS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Human_resource_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_master_PDF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.human_resource')),
                ('id_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.year_hr')),
            ],
        ),
        migrations.CreateModel(
            name='Event_connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('id_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.year_event')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.budget')),
                ('id_faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
        ),
    ]
