# Generated by Django 3.2.7 on 2021-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211013_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_leave',
            name='end',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='study_leave',
            name='extend_begin',
            field=models.DateField(blank=True, default=None),
        ),
    ]
