# Generated by Django 3.2.7 on 2021-10-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211013_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='position_request',
        ),
        migrations.AddField(
            model_name='pending',
            name='request_position',
            field=models.CharField(blank=True, choices=[('ศาสตราจารย์', 'ศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('เชี่ยวชาญ', 'เชี่ยวชาญ'), ('ชำนาญการพิเศษ', 'ชำนาญการพิเศษ'), ('ชำนาญการ', 'ชำนาญการ')], max_length=100, null=True),
        ),
    ]
