# Generated by Django 3.2.8 on 2021-10-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211014_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_degree',
            name='degree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.degree'),
        ),
        migrations.AlterField(
            model_name='user_degree',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
